### ISSUE TITLE
event list output needs to be chronological

### ISSUE THREAD

**Issue by grungerabbit** [TechAtNYU/cal#1]
![screenshot 2015-10-06 21 50 29](https://cloud.githubusercontent.com/assets/1840745/10327345/4fc39936-6c74-11e5-86b4-bac95bd165bc.png)

output is based on when things are added to API, even if an event is added later but is temporally before (see: After Hours on Wednesday vs. DemoDays on Thursday)

**Comment by AbhiAgarwal** [comment]
You can add the parameter `?page%5Blimit%5D=10&sort=%2bstartDateTime` to sort it

**Comment by oa495** [comment]
![screen shot 2015-10-08 at 10 42 48 am](https://cloud.githubusercontent.com/assets/8635106/10369664/695600e2-6da9-11e5-9184-b6f595e42167.png)

**Comment by terriburns** [comment]
ayyyyyy
i'm so excited about this :dancer:
