### ISSUE TITLE
cal shows events that are still listed as 'draft' from /events

### ISSUE THREAD

**Issue by ycp217** [TechAtNYU/cal#17]
altho im not sure how important this is

**Comment by ycp217** [comment]
might run into trouble if we have events listed as drafts that are just for testing purposes/other things

**Comment by oa495** [comment]
mm. so when you list an event on the intranet, the status field is always blank even if you edit and change it to published. So, when I'm getting the events the status field is undefined/null and I can't filter with that.

**Comment by ethanresnick** [comment]
> so when you list an event on the intranet, the status field is always blank even if you edit and change it to published.

Yeah, this is a limitation of the intranet that'll hopefully be fixed soon. That is, the intranet's list page can't show field values that point to other resource types. But if you go to the edit page, the value does show up, and it is actually being saved/exposed by the api. So the only events that should have status `null` are those where it hasn't been set. (And even that's probably a bug, so I've opened an [issue](https://github.com/TechAtNYU/api/issues/150) for it.) 

So it should be possible to filter out draft events. There are a couple complications that would come from asking the api to do the filtering for you (i.e., with a query param), but it should be possible to do it manually in the code.

**Comment by oa495** [comment]
![screen shot 2015-11-27 at 11 06 43 pm](https://cloud.githubusercontent.com/assets/8635106/11450041/99f5370c-955b-11e5-99dd-9fd4e0b479be.png)

so these are all the attributes that come with an event. there's no 'status' attribute.

**Comment by ethanresnick** [comment]
Right. In API v2, `status` is a relationship rather than a simple attribute, so it's under the `"links"` key instead (with venue and all the other relationships). 

There was a rationale for this originally (related to meetup service), but things were simplified in v3 to make status a simple attribute. But until then, just look in `"links"`

**Comment by oa495** [comment]
a22bd05
