### ISSUE TITLE
broken in firefox 42.0

### ISSUE THREAD

**Issue by AbhiAgarwal** [TechAtNYU/cal#19]
hi! I was using firefox today and I noticed that this was broken on it :( 

![broken](http://files.tnyu.org/upload_784d0123215c881ea428c7f706fa7a5f_g.png)

**Comment by oa495** [comment]
![screen shot 2016-01-22 at 10 43 51 am](https://cloud.githubusercontent.com/assets/8635106/12515176/130650c6-c0f5-11e5-9fe5-15cd2abdcba4.png)

fixed. tested on firefox 36.0.1 and 42.0
