### ISSUE TITLE
text overlap

### ISSUE THREAD

**Issue by terriburns** [TechAtNYU/cal#20]
google chrome full screen (mac 13th inch), happens 100% of the time, on each month

![screen shot 2015-12-26 at 8 44 19 pm](https://cloud.githubusercontent.com/assets/7284203/12008886/b38f9fbe-ac11-11e5-8190-0c30090beb04.png)

**Comment by oa495** [comment]
hey terri, if you have access, could you check this again?

**Comment by terriburns** [comment]
@oa495 still happening.

**Comment by oa495** [comment]
think this should be fixed?

**Comment by terriburns** [comment]
looks perf :100:
