### ISSUE TITLE
Distinction of events that have happened on the right bar?

### ISSUE THREAD

**Issue by AbhiAgarwal** [TechAtNYU/cal#5]
Can we do like upcoming vs done here too? Just curious if that makes sense to both of you since the newer events will get bogged down, and there should be a way to highlight them that is nice! I'd love to hear your thoughts!

I totally understand that it's a calendar. But, it's just hard for me to distinguish between what has happened and what is going to happen.

![](http://files.tnyu.org/upload_fe77270929576e352e79a16af232607f_g.png)

**Comment by grungerabbit** [comment]
yes, definitely! I wanted to address this soon. @oa495 is taking a brief break because of midterms, but I'll see what I can do (it should be pretty easy, like just greying out the past events)

**Comment by oa495** [comment]
so a few options: we could do
1) opacity: so past events are greyed out (but they would still be at the top and users will have to scroll to see upcoming events)
2) sort options - upcoming | past
3) sort option: just have upcoming events at the top
4) we have colors like this, so maybe tiny green boxes by the event that have passed and then another color for upcoming (then at the top we can indicate what those colors mean) & then we could also sort by colors.

I'm fine with 2, 3, 4. let me know what you think is best (I'm working on it now) @AbhiAgarwal @grungerabbit
