### ISSUE TITLE
Correlate sidebar event with calendar block

### ISSUE THREAD

**Issue by ycp217** [TechAtNYU/cal#6]
Is it possible to do a thing where when you hover over the event the correlating block on the calendar lights up or something? Or overlay event shortTitle on the calendar block so ppl know which event description goes with which day?

**Comment by grungerabbit** [comment]
yassss both really good ideas, do you wanna take a look at it with me at infra tonight?

**Comment by ycp217** [comment]
yeah, lets do that! :ok_woman:

**Comment by oa495** [comment]
@ycp217 what works better? Hover to see corresponding event or click?

**Comment by ethanresnick** [comment]
hover won't work on touch devices, fwiw

**Comment by oa495** [comment]
click it is
